ifndef::imagesdir[:imagesdir: ../images]

[[section-building-block-view]]

== Building block view

=== Level 1: Overall System's whitebox

[plantuml,"Level 1 Diagram",png]
----
!pragma layout smetana

:User: -> [WIQ App] : "Interacts with"
[WIQ App] <.> [WikiData] : "Gets data"
----


==== Motivation

This level shows how the application will work internally in generaly. The client, WebApp, access to the different services provided by the microservices which make up the program.

==== Contained Building Blocks

[options="header"]
[cols="1,4"]
|===
|Name |Description
|_User_
|Client of the application which will interact with it.
|_WIQ App_
|System developed to be used by the users. The games will be based on the information obtained from WikiData.
|_WikiData_
|Service external to the application from which the application questions will be obtained. Wikidata is a collaboratively edited multilingual knowledge graph hosted by the Wikimedia Foundation.
|===


=== Level 2

[plantuml,"Level 2 Diagram",png]
----
!pragma layout smetana

:User:
package "WIQ App" {
:User: -> [WebApp] : " Interacts    "
[WebApp] <-> [Gateway Service] : Redirects Requests
[Gateway Service] <--down-> [Game Service] : Plays
[Gateway Service] <-- [Store Question Service] : Loads data
[Gateway Service] <-- [User Stats Service] : Loads data
[Gateway Service] <-> [UserAuth Service] : Logs in / Registers
[Game Service] -> [User Stats Service] : Stores data
[Game Service] <-left-> [Questions Service] : Gets questions
[Questions Service] -up-> [Store Question Service] : Stores data
}
[Questions Service] <.left.> [WikiData] : "  Gets data  "
----

==== Motivation

*_WiQ_* application is the general structure of a system in which users will have the possibility to play a video game implementation of the popular RTVE programme, "Saber y Ganar". 

==== Contained Building Blocks

[cols="1,4" options="header"]
|===
|Name |Description
|_Web App_ |Layer in which the user will interact directly and which will connect with the different services.
|_Gateway Service_ |Microservice that redirects the requests from the WebApp to its corresponding microservices
|_Questions Service_ |Microservice to generate the questions used by the application from WikiData
|_Game Service_ |Microservice that implements the quiz game
|_Question Historic Service_ |Microservice that stores the generated questions for later consultation
|_User Statistics Service_ |Microservice that stores the statistics of the games played by the user.
|_UserAuth Service_ |Authentication microservices that allows the user to register and log in.
|===

=== Level 3

[plantuml,"Level 3 Diagram",png]
----
!pragma layout smetana

actor "User"
rectangle "Wikidata"

package "WIQ App"{

    component "WebApp"
    component "Gateway Service" as GatewayS

    component "Game Service" 
        package "Store Question Service" as QHS{
        component "Store-Q Service" as QHController
        database "storedquestion" as QhDB
    }
    package "User Stats Service" as USS {
        component "User Stats Service"
        database " statsdb " as USDB
    }
    package "UserAuth Service" {
        component "Auth Service"
        component "User Service"
        database "userdb" as UADB
    }

    package "Questions Service"{
        component "Wikidata Extractor"
        component "Questions Generator Service"
        database "questions" as QSDB
    }
}

User -right-> WebApp : Uses
WebApp <-right-> GatewayS: Redirects requests

GatewayS <--up--> "UserAuth Service" : "Handles user\nlogin/registry"
GatewayS <-down-> "Game Service" : "Handles user current game"
GatewayS <--up-- "QHS" : "\nReceives generated\nquestions"
GatewayS <--- "USS" : "Receives\t\t\t\nuser statistics\t\t\t"

"Game Service" <---> "Questions Service" : "Receives question petitions,\nsends questions\n\n"
"Game Service" ---> "USS" : "Sends user\t\nstatistics\t\t"
"Questions Service" -up-> "QHS" : " Sends\n  generated\n  questions"

"Wikidata" .up.> "Wikidata Extractor" : "Returns data"
"Wikidata" <.up. "Wikidata Extractor" : "Queries"
"Wikidata Extractor" --> QSDB
"Questions Generator Service" <-- QSDB
"Questions Generator Service" --> QSDB

"QHController" --> QhDB
"QHController" <-- QhDB

"User Stats Service" --> USDB
"User Stats Service" <-- USDB

"Auth Service" --> UADB
"Auth Service" <-- UADB
"User Service" --> UADB
"User Service" <-- UADB
----

==== Motivation

To display the inner architecture of the different microservices, as well as how do their components interact with themselves and with other components from other microsystems. All microservices follow the MVC architectural pattern, to the exception of those who have no UI to handle.

==== Contained Building Blocks

[cols="1,4" options="header"]
|===
|Name |Description

|_User Service_
|It retrieves the data from new users and registers them in the database.

|_Auth Service_
|It retrieves the data from returning users and checks if they are in the database.

|_Game Controller_
|Handles all the game’s logic; where the user input’s processing takes place. It can request questions to the Questions Microservice, and also gather user statistics, to later be sent to the User Statistics Controller.

|_Questions Historic Controller_
|Receives the generated questions, and sends them to the database. Besides, it also handles recovering them from the database and sending them where they are needed. (e.g: as response from an API call, or to the UI)

|_User Statistics Controller_
|Receives various information about the player’s performance in the match. There, some processing may occur before storing it in the database. Also handles retrieving the information and sending it where it’s needed (e.g: as response from an API call, or to the UI).

|_Questions Generator_
|Contains the required templates and proceedings to construct questions. In order to do so, it delegates the Wikidata querying to the Wikidata extractor. It gets the data through the database so when the data is returned, the question is formulated through templates. 

|_Wikidata Extractor_
|Handles extraction and formatting of Wikidata’s output. It’s queries must cover all necessary information in order to construct the question(s), including not only the correct response, but also believable and coherent “decoy answers”. It stores the data retrieved on the database.
|===
